# Automatically updated by the winget bot at 2021/Jun/18
PackageIdentifier: Google.Chrome
PackageVersion: custom1
MinimumOSVersion: 10.0.0.0
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
Commands:
- chrome
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi
  InstallerSha256: 440D0B77FAEC319CA10D9A6523F4846222F2EF4395DA848E472868820B5FF862
  ProductCode: "{0E791EC0-B7AF-3E47-92EE-C435F246738A}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0